set(FILES
    Source/Scene/Behaviors/AudioEventGroupBehavior.cpp
    Source/Scene/Behaviors/AudioEventGroupBehavior.h
    Source/Scene/Generators/SteamAudioGenerationComponent.cpp
    Source/Scene/Generators/SteamAudioGenerationComponent.h
    Source/Scene/Groups/AudioEventGroup.cpp
    Source/Scene/Groups/AudioEventGroup.h
    Source/Scene/Processors/AudioEventProcessor.cpp
    Source/Scene/Processors/AudioEventProcessor.h
)
