
set(FILES
    Source/SteamAudioModuleInterface.cpp
    Source/SteamAudioModuleInterface.h

    Source/Clients/SteamAudioSystemComponent.cpp
    Source/Clients/SteamAudioSystemComponent.h

    Source/Engine/AudioInput/AudioInputFile.cpp
    Source/Engine/AudioInput/AudioInputFile.h
    Source/Engine/AudioInput/WavParser.cpp
    Source/Engine/AudioInput/WavParser.h

    Source/Engine/ATLEntities_steamaudio.h
    Source/Engine/AudioEventBus.h
    Source/Engine/AudioSource.cpp
    Source/Engine/AudioSource.h
    Source/Engine/AudioSourceManager.cpp
    Source/Engine/AudioSourceManager.h
    Source/Engine/AudioSystemImplementation_steamaudio.cpp
    Source/Engine/AudioSystemImplementation_steamaudio.h
    Source/Engine/Common_steamaudio.h
    Source/Engine/Configuration.cpp
    Source/Engine/Configuration.h
    Source/Engine/ISoundEngine.h
    Source/Engine/MaSoundEngine.cpp
    Source/Engine/MaSoundEngine.h
    Source/Engine/Parameters.h
    Source/Engine/SaAudioObject.cpp
    Source/Engine/SaAudioObject.h
    Source/Engine/SaAudioObjectBus.h
    Source/Engine/SaEvent.cpp
    Source/Engine/SaEvent.h
    Source/Engine/SaEventAsset.cpp
    Source/Engine/SaEventAsset.h
    Source/Engine/SaEventAssetHandler.cpp
    Source/Engine/SaEventAssetHandler.h
    Source/Engine/SaRegisteredEvent.cpp
    Source/Engine/SaRegisteredEvent.h
    Source/Engine/SaRegisteredEventBus.h
    Source/Engine/SaSoundAsset.cpp
    Source/Engine/SaSoundAsset.h
    Source/Engine/SaSoundInstance.cpp
    Source/Engine/SaSoundInstance.h
    Source/Engine/SaSoundSource.cpp
    Source/Engine/SaSoundSource.h
    Source/Engine/SaSoundSourceAsset.cpp
    Source/Engine/SaSoundSourceAsset.h
    Source/Engine/SaSoundSourceAssetHandler.cpp
    Source/Engine/SaSoundSourceAssetHandler.h
    Source/Engine/SaSoundSourceBus.h
    Source/Engine/SoundBankAssetHandler.cpp
    Source/Engine/SoundBankAssetHandler.h
    Source/Engine/SoundConfig.cpp
    Source/Engine/SoundConfig.h
    Source/Engine/SoundSourceLoader.cpp
    Source/Engine/SoundSourceLoader.h

    Source/Engine/Parsing/AudioEventXmlParser.cpp
    Source/Engine/Parsing/AudioEventXmlParser.h
)
